# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        !profile {
            LIBS += -lactiontriggercommon

            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }

    CONFIG(release, debug|release) {
        !profile {
            LIBS += -lactiontriggercommon

            CONFIG += \
                config_pri_assets \
                config_pri_source_group2
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            LIBS += -lactiontriggercommon

            CONFIG += \
                config_pri_assets \
                config_pri_source_group2
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/ActiveCover.qml) \
        $$quote($$BASEDIR/assets/Border.qml) \
        $$quote($$BASEDIR/assets/Catalog.qml) \
        $$quote($$BASEDIR/assets/Debug.qml) \
        $$quote($$BASEDIR/assets/DefaultActivity.qml) \
        $$quote($$BASEDIR/assets/DefaultContainer.qml) \
        $$quote($$BASEDIR/assets/DefaultPageContainer.qml) \
        $$quote($$BASEDIR/assets/DialogSelectVariable.qml) \
        $$quote($$BASEDIR/assets/Editor.qml) \
        $$quote($$BASEDIR/assets/GetProfileConfirm.qml) \
        $$quote($$BASEDIR/assets/Headless.qml) \
        $$quote($$BASEDIR/assets/Help.qml) \
        $$quote($$BASEDIR/assets/HorizontalLine.qml) \
        $$quote($$BASEDIR/assets/Indent.qml) \
        $$quote($$BASEDIR/assets/Library.qml) \
        $$quote($$BASEDIR/assets/NonStandardListItem.qml) \
        $$quote($$BASEDIR/assets/OverviewTab.qml) \
        $$quote($$BASEDIR/assets/ParameterBase.qml) \
        $$quote($$BASEDIR/assets/ParameterCheckbox.qml) \
        $$quote($$BASEDIR/assets/ParameterDirDialog.qml) \
        $$quote($$BASEDIR/assets/ParameterDropdown.qml) \
        $$quote($$BASEDIR/assets/ParameterDropdownFilter.qml) \
        $$quote($$BASEDIR/assets/ParameterFileDialog.qml) \
        $$quote($$BASEDIR/assets/ParameterLabel.qml) \
        $$quote($$BASEDIR/assets/ParameterSlider.qml) \
        $$quote($$BASEDIR/assets/ParameterString.qml) \
        $$quote($$BASEDIR/assets/ParameterText.qml) \
        $$quote($$BASEDIR/assets/ParameterTime.qml) \
        $$quote($$BASEDIR/assets/ParameterTriggerValue.qml) \
        $$quote($$BASEDIR/assets/ParameterVariable.qml) \
        $$quote($$BASEDIR/assets/Permissions.qml) \
        $$quote($$BASEDIR/assets/Procedure.qml) \
        $$quote($$BASEDIR/assets/SelectVariable.qml) \
        $$quote($$BASEDIR/assets/Services.qml) \
        $$quote($$BASEDIR/assets/Settings.qml) \
        $$quote($$BASEDIR/assets/Space.qml) \
        $$quote($$BASEDIR/assets/Statement.qml) \
        $$quote($$BASEDIR/assets/StatementPicker.qml) \
        $$quote($$BASEDIR/assets/Support.qml) \
        $$quote($$BASEDIR/assets/Test.qml) \
        $$quote($$BASEDIR/assets/TutorialList.qml) \
        $$quote($$BASEDIR/assets/actiontrigger.db) \
        $$quote($$BASEDIR/assets/images/bb10/ic_add.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_add_entry.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_add_favorite.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_add_folder.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_add_to_contacts.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_advanced.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_advanced_restore.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_all.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_attach.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_bbm.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_browse.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_browser.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_buy.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_camera.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_cancel.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_cancel_selection.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_check_spelling.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_clear.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_clear_list.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_code_inspector.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_collapse.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_compose.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_connections.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_contacts.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_copy.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_copy_link.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_copy_link_image.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_copy_password.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_cut.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_decrease.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_delete.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_delete_prior.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_deselect.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_deselect_all.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_diagnostics.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_disable.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_doc.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_generic.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_music.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_pdf.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_picture.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_ppt.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_video.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_web.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_xls.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_doctype_zip.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_done.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_download.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_edit.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_edit_favorite.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_edit_list.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_edit_profile.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_email.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_enable.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_entry.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_expand.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_favorite.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_feedback.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_forward.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_forward_as_bbm.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_forward_as_email.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_forward_as_text.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_help.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_history.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_home.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_increase.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_info.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_location.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_lock.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_map.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_microphone.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_microphone_mute.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_move.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_nav_to.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_next.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_notes.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_notification.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_open.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_open_link.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_overflow_action.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_overflow_tab.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_paste.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_pause.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_phone.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_play.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_previous.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_properties.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_reload.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_rename.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_reply.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_reply_all.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_rotate.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_save.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_save_as.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_scan_barcode.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_search.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_select.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_select_all.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_select_more.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_select_text.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_select_text_all.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_set_as_default.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_settings.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_share.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_show_dialpad.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_show_vkb.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_sort.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_sort_filter.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_speaker.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_speaker_mute.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_stop.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_textmessage.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_to_bottom.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_to_top.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_view_details.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_view_grid.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_view_image.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_view_list.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_view_post.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_zoom_in.png) \
        $$quote($$BASEDIR/assets/images/bb10/ic_zoom_out.png) \
        $$quote($$BASEDIR/assets/images/custom/ic_move_down.png) \
        $$quote($$BASEDIR/assets/images/custom/ic_move_up.png) \
        $$quote($$BASEDIR/assets/logo/FeatureImage1920x1186.png) \
        $$quote($$BASEDIR/assets/logo/ProcedureIcon480x480.png) \
        $$quote($$BASEDIR/assets/logo/ProductIcon480x480.png) \
        $$quote($$BASEDIR/assets/logo/Splash720x720.png) \
        $$quote($$BASEDIR/assets/logo/background1920x1186.png) \
        $$quote($$BASEDIR/assets/logo/favicon.ico) \
        $$quote($$BASEDIR/assets/logo/splash1280x720.png) \
        $$quote($$BASEDIR/assets/logo/splash1280x768.png) \
        $$quote($$BASEDIR/assets/logo/splash720x1280.png) \
        $$quote($$BASEDIR/assets/logo/splash768x1280.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/model.xml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/applicationwrapper.cpp) \
        $$quote($$BASEDIR/src/asyncappload.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/mylistmodel.cpp) \
        $$quote($$BASEDIR/src/qmlbeam.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/applicationui.hpp) \
        $$quote($$BASEDIR/src/applicationwrapper.hpp) \
        $$quote($$BASEDIR/src/asyncappload.hpp) \
        $$quote($$BASEDIR/src/mylistmodel.hpp) \
        $$quote($$BASEDIR/src/qmlbeam.hpp)
}

config_pri_source_group2 {
    SOURCES += \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/applicationwrapper.cpp) \
        $$quote($$BASEDIR/src/asyncappload.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/mylistmodel.cpp) \
        $$quote($$BASEDIR/src/qmlbeam.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/applicationui.hpp) \
        $$quote($$BASEDIR/src/applicationwrapper.hpp) \
        $$quote($$BASEDIR/src/asyncappload.hpp) \
        $$quote($$BASEDIR/src/mylistmodel.hpp) \
        $$quote($$BASEDIR/src/qmlbeam.hpp)
}

INCLUDEPATH += $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/bb10/*.qml) \
        $$quote($$BASEDIR/../assets/images/bb10/*.js) \
        $$quote($$BASEDIR/../assets/images/bb10/*.qs) \
        $$quote($$BASEDIR/../assets/images/custom/*.qml) \
        $$quote($$BASEDIR/../assets/images/custom/*.js) \
        $$quote($$BASEDIR/../assets/images/custom/*.qs) \
        $$quote($$BASEDIR/../assets/logo/*.qml) \
        $$quote($$BASEDIR/../assets/logo/*.js) \
        $$quote($$BASEDIR/../assets/logo/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
